version: '2.1'
orbs:
  flutter: circleci/flutter@2.0.0
jobs:
  build:
    executor:
      name: android/android-machine
    steps:
      - flutter/install_sdk_and_pub:
          version: 3.7.9
      - run: bundle -h
