version: '2.1'
orbs:
  flutter: circleci/flutter@2.0.0
jobs:
  mac-os:
    parameters:
      version:
        default: ""
        type: string
    macos:
      xcode: << parameters.version >>
    resource_class: macos.x86.medium.gen2
    steps:
      - run:
          name: check before $PATH
          command: echo $PATH
          when: always 
      - run: echo "export PATH=~/project/flutter/bin:$PATH" >> "$BASH_ENV"
      - run:
          name: check after $PATH
          command: echo $PATH
          when: always 
      - run: rbenv -v

     
workflows:
  build:
    jobs:
      - mac-os:
          matrix:
            parameters:
              version: ["14.1.0","14.2.0", "14.3.0"]
